# Generated by Django 5.2.6 on 2025-09-29 01:09

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogBookField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("number", "Number"),
                            ("integer", "Integer"),
                            ("text", "Text"),
                            ("longtext", "Long Text"),
                            ("bool", "True/False"),
                            ("date", "Date"),
                            ("time", "Time"),
                            ("datetime", "Date + Time"),
                            ("choice", "Choice"),
                            ("multi", "Multi"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("help_text", models.CharField(blank=True, max_length=200)),
                ("unit", models.CharField(blank=True, max_length=24)),
                ("order", models.PositiveIntegerField(default=0)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("decimals", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("choices", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="entry",
            name="content",
        ),
        migrations.RemoveField(
            model_name="entry",
            name="title",
        ),
        migrations.AddField(
            model_name="entry",
            name="data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="entry",
            name="note",
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["data"], name="gin_entry_data"
            ),
        ),
        migrations.AddField(
            model_name="logbookfield",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="logbooks.logbook",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="logbookfield",
            unique_together={("book", "slug")},
        ),
    ]
