# Generated by Django 5.2.6 on 2025-09-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0002_logbookfield_remove_entry_content_remove_entry_title_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logbookfield',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='logbookfield',
            name='book',
        ),
        migrations.RemoveIndex(
            model_name='entry',
            name='gin_entry_data',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='note',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='data',
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.DeleteModel(
            name='LogBookField',
        ),
    ]
