# Generated by Django 5.2.6 on 2025-10-03 00:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbooks", "0005_entry_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="number_array",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.DecimalField(decimal_places=3, max_digits=18),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="entry",
            name="number",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=18, null=True
            ),
        ),
    ]
