# Generated by Django 5.2.6 on 2025-10-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logbooks", "0005_entry_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="number_array",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name="entry",
            name="number",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=18, null=True
            ),
        ),
    ]
